/**
 * Import buildings from halifax_buildings.csv into Supabase.
 *
 * CSV columns: id, name, height_m, footprint_wkt, source_dataset
 * The footprint_wkt column contains WKT POLYGON geometry.
 *
 * Run: npx tsx scripts/import-buildings.ts
 *
 * Requires:
 *   - data/halifax_buildings.csv (generated by Phase 0 DuckDB/Overture query)
 *   - NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY env vars
 */

import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? ''
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY ?? ''

if (!supabaseUrl || !serviceRoleKey) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, serviceRoleKey)

const SOURCE_MAP: Record<string, string> = {
  OpenStreetMap: 'osm',
  overture: 'overture',
  lidar: 'lidar',
  manual: 'manual',
}

function parseCSVLine(line: string): string[] {
  const fields: string[] = []
  let current = ''
  let inQuotes = false

  for (let i = 0; i < line.length; i++) {
    const char = line[i]
    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"'
        i++
      } else {
        inQuotes = !inQuotes
      }
    } else if (char === ',' && !inQuotes) {
      fields.push(current)
      current = ''
    } else {
      current += char
    }
  }
  fields.push(current)
  return fields
}

async function importBuildings() {
  const csv = readFileSync('data/halifax_buildings.csv', 'utf-8')
  const lines = csv.split('\n').filter((l) => l.trim().length > 0)

  // Skip header: id,name,height_m,footprint_wkt,source_dataset
  const dataLines = lines.slice(1)
  console.log(`Importing ${dataLines.length} buildings...`)

  // Clear existing buildings to avoid duplicates on re-run
  const { error: deleteError } = await supabase.from('buildings').delete().neq('id', '00000000-0000-0000-0000-000000000000')
  if (deleteError) {
    console.error('Warning: could not clear existing buildings:', deleteError.message)
  }

  const BATCH_SIZE = 50
  let imported = 0
  let skipped = 0
  let errors = 0

  for (let i = 0; i < dataLines.length; i += BATCH_SIZE) {
    const batch = dataLines.slice(i, i + BATCH_SIZE)
    const rows = batch
      .map((line) => {
        const fields = parseCSVLine(line)
        if (fields.length < 5) return null

        const [sourceId, , heightStr, footprintWkt, sourceDataset] = fields
        const height = heightStr && heightStr !== '' ? parseFloat(heightStr) : null

        if (!footprintWkt || !footprintWkt.startsWith('POLYGON')) {
          skipped++
          return null
        }

        const source = SOURCE_MAP[sourceDataset?.trim()] ?? 'osm'

        return {
          footprint: `SRID=4326;${footprintWkt}`,
          height_m: height != null && !isNaN(height) ? height : null,
          source,
          source_id: sourceId || null,
        }
      })
      .filter(Boolean)

    if (rows.length === 0) continue

    const { error } = await supabase.from('buildings').insert(rows)

    if (error) {
      console.error(`Batch ${Math.floor(i / BATCH_SIZE) + 1} error:`, error.message)
      errors += batch.length
    } else {
      imported += rows.length
      process.stdout.write(`\r  Imported ${imported}/${dataLines.length}...`)
    }
  }

  console.log(`\nDone! Imported ${imported}, skipped ${skipped}, errors ${errors}.`)
}

importBuildings().catch(console.error)
